### ISSUE TITLE
Getting issue with slop and banner

### ISSUE THREAD

**Issue by charlesrg** [ytti/netcrawl#1]
undefined method `banner' for #<NetCrawl::CLI:0x000000024b8050>
/usr/local/rvm/gems/ruby-2.2.0/gems/netcrawl-0.0.8/lib/netcrawl/cli.rb:42:in`block in opt_parse': undefined method `banner' for #<NetCrawl::CLI:0x000000024b8050> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.2.0/gems/slop-4.0.0/lib/slop/options.rb:33:in`initialize'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/slop-4.0.0/lib/slop.rb:24:in `new'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/slop-4.0.0/lib/slop.rb:24:in`parse'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/netcrawl-0.0.8/lib/netcrawl/cli.rb:41:in `opt_parse'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/netcrawl-0.0.8/lib/netcrawl/cli.rb:30:in`initialize'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/netcrawl-0.0.8/bin/netcrawl:5:in `new'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/netcrawl-0.0.8/bin/netcrawl:5:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.0/bin/netcrawl:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.0/bin/netcrawl:23:in`<main>'
        from /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in`<main>'

Here is the install info:
 gem install netcrawl
Fetching: snmp-1.2.0.gem (100%)
Successfully installed snmp-1.2.0
Fetching: slop-4.0.0.gem (100%)
Successfully installed slop-4.0.0
Fetching: asetus-0.2.0.gem (100%)
Successfully installed asetus-0.2.0
Fetching: netcrawl-0.0.8.gem (100%)
Successfully installed netcrawl-0.0.8
Parsing documentation for snmp-1.2.0
Installing ri documentation for snmp-1.2.0
Parsing documentation for slop-4.0.0
Installing ri documentation for slop-4.0.0
Parsing documentation for asetus-0.2.0
Installing ri documentation for asetus-0.2.0
Parsing documentation for netcrawl-0.0.8
Installing ri documentation for netcrawl-0.0.8
Done installing documentation for snmp, slop, asetus, netcrawl after 1 seconds
4 gems installed

Are you using a different version of slop ?

**Comment by charlesrg** [comment]
Looks like slop 4.0.0 broke it.  It seems to work with 3.6.0

**Comment by ytti** [comment]
I have this issue in plethora of packages due to lazy versioning. 

I've uploaded 0.1.0 which specifies appropriate version for slop.
