### ISSUE TITLE
Source Interfaces Empty

### ISSUE THREAD

**Issue by yantisj** [ytti/netcrawl#2]
I installed netcrawl on an Ubuntu 14.04 machine via gem, and I seem to have a problem with source interfaces not populating across a wide range of devices. This seems to be causing issues for the json and yaml output as well. When I output everything as a hash, here's what I see:

```
   {"ip"=>"10.25.0.18",
    "name"=>"10.25.0.18",
    "interface"=>{"source"=>"", "destination"=>"GigabitEthernet1/0/10"},
    "raw"=>{"ip"=>"\n\x19\x00\x12", "name"=>"CoreA_H968_3750X"}},
```

Every interface source is blank on all of our devices, no matter what the model is.

Any help would be appreciated, because otherwise this seems to be a great program for some work I'm doing.

Thanks!

**Comment by ytti** [comment]
Can I get SNMP/CDP/LLDP access to some sanitised device so I can reproduce the behaviour and hopefully fix the code?

**Comment by yantisj** [comment]
Hey, I'll set something up on Tuesday that's open to the world for testing. Thanks, this could be really useful for a project I'm working on.

**Comment by yantisj** [comment]
FYI, I setup a minimal configuration switch externally and tested it via an AWS instance, and of course everything worked. I suspect something with our SNMP configuration may be causing this issue, so I'm going to do some more testing before I post back here. Thanks

**Comment by yantisj** [comment]
After some more extensive testing, it seems most of the issues are related to Nexus devices, as well as Catalyst 4500s where the source interface is often blank or has the interface description in the source interface field. I'll see what I can do to setup a publicly accessible lab for some of this, but it may be difficult. Give me a day or so to see if I can come up with something. Thanks again

**Comment by ytti** [comment]
Any update?

**Comment by yantisj** [comment]
Hey sorry, I'm going to have to close this one. I tried several of our devices, and was getting inconsistent results that I can't explain. I have an SSH based scraper, that while not as efficient, I'm going to have to stick with that for now.

Thanks for following up though!
Jonathan

**Comment by ytti** [comment]
Ok. Let me know if you want to give it another go and want my help. I you dare to give access to live environment or just SNMP access from 91.198.120.1, I'm happy to troubleshoot this.

**Comment by yantisj** [comment]
Much appreciated, that’s what I was looking into but given our security environment, I’d never be able to get it approved.

Thanks again!
